### ISSUE TITLE
Api: 500 Server error

### ISSUE THREAD

**Issue by Jelmergu** [joostlawerman/PHPLogboek#12]
Postman Collection: https://www.getpostman.com/collections/e8adf6c05d1eea5470f6

**Comment by joostlawerman** [comment]
Gooi nog ff de api route erbij.

**Comment by MaartenGDev** [comment]
https://laravel.com/docs/5.3/errors#the-exception-handler

**Comment by joostlawerman** [comment]
https://laracasts.com/discuss/channels/code-review/best-way-to-handle-rest-api-errors-throwed-from-controller-or-exception

**Comment by Jelmergu** [comment]
Failure @ /api/group/1/course/1

**Comment by Jelmergu** [comment]
Okee, ben er achter dat dit elke keer een error is die voortkomt uit een dubbele primary key in de database
