### ISSUE TITLE
Login forgot password

### ISSUE THREAD

**Issue by joostlawerman** [joostlawerman/PHPLogboek#4]
Login forgot password..

- [ ] Backend
    - Staat standaard in laravel
- [x] Frontend
    - Fix met javascirpt

**Comment by skanon97** [comment]
verkeerd geklikt

**Comment by ThomLSA** [comment]
Goedemiddag collega's, 
Bij deze de 'Login forgot password` pagina's. ;_;

Vergeten van wachtwoord pagina

```
 <div class="login-clean" style="padding-top:15%;">
        <form method="post">
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><img src="aventuslogo.png" style="max-height:155px;" /></div>
            <div class="form-group"></div>
            <p class="text-center">Wachtwoord vergeten</p>
            <div class="form-group">
                <input type="password" name="emailforgot" required placeholder="Uw e-mail adres" class="form-control" />
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Stuur e-mail</button>
            </div><a href="#" class="forgot">Ga terug</a></form>
    </div>
```

Na e-mail ontvangen te hebben, wachtwoord instel pagina.

    <div class="login-clean">
        <form method="post">
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><img src="aventuslogo.png" style="max-height:155px;" /></div>
            <div class="form-group"></div>
            <p class="text-center">Wachtwoord opnieuw instellen</p>
            <div class="form-group">
                <input type="password" name="emailforgot" required placeholder="Wachtwoord" class="form-control" style="margin-bottom:10px;" />
                <input type="password" name="emailforgot" required placeholder="Herhaal wachtwoord" class="form-control" />
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Wachtwoord wijzigen</button>
            </div>
        </form>
    </div>

**Comment by R0vi** [comment]
ik heb nu met zelfde css als login page gebruikt ik neem aan dat dat de goeie is. aangezien dit er niet bij staat.

**Comment by R0vi** [comment]
done.

**Comment by ThomLSA** [comment]
@R0vi Ja klopt, dit is allemaal hetzelfde.

**Comment by sandergielen** [comment]
Goed gedaan! 💯
