### ISSUE TITLE
Inlog error afvangen

### ISSUE THREAD

**Issue by reinbertOK** [joostlawerman/PHPLogboek#41]
http://prntscr.com/dv65po

spreekt voor zich :)

**Comment by ThomLSA** [comment]
Is dit een Front-end #1 issue?

**Comment by reinbertOK** [comment]
euhm, ja eigenlijk wel. als jullie gewoon een mooie error page kunnen maken. inhoud fixed backend wel

**Comment by ThomLSA** [comment]
Komt voor mekaar! @reinbertOK

**Comment by reinbertOK** [comment]
top

**Comment by reinbertOK** [comment]
nvm. werkt al :D
