### ISSUE TITLE
Gebruikers import pagina

### ISSUE THREAD

**Issue by joostlawerman** [joostlawerman/PHPLogboek#7]
- [x] lijst met gebruikers
- [x] import knop om csv te uploaden en als gebruikers te importeren zie voorbeeld 
| naam | email | klas | rol |
vraag mij maar om hulp voor de import nadat je de interface en routes af hebt -- @joostlawerman

**Comment by reinbertOK** [comment]
@joostlawerman  kan je dezen aan backend project koppelen?

**Comment by joostlawerman** [comment]
@skanon97 is hier mee bezig als het goed is

**Comment by reinbertOK** [comment]
ja, klopt, maar ik kan de issue niet aan project koppelen

**Comment by niels666** [comment]
Registratie pagina gebruikers via formulier
Registratie pagina CSV bestand upload gecommit.

**Comment by reinbertOK** [comment]
@niels666 front end gedeelte? of ook backend? ik meen dat @skanon97  nog bezig was met backend

**Comment by niels666** [comment]
Frontend alleen van mijn kant, excuses.

**Comment by reinbertOK** [comment]
np, top. lekker bezig :D

**Comment by joostlawerman** [comment]
@skanon97 
https://github.com/joostlawerman/PHPLogboek/commit/d20129ca14c9f7c92a9c253eea08b95b0d5960b0

**Comment by skanon97** [comment]
Database connectie moet nog, zou ik graag hulp bij willen @joostlawerman ?

**Comment by joostlawerman** [comment]
Kom er zo aan

On Fri, Jan 20, 2017, 1:30 PM Stijn Kanon <notifications@github.com> wrote:

Database connectie moet nog, zou ik graag hulp bij willen @joostlawerman
<https://github.com/joostlawerman> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joostlawerman/PHPLogboek/issues/7#issuecomment-274061528>,
or mute the thread

**Comment by skanon97** [comment]
Gemaakt, HTML en css moeten alleen nog ff worden toegevoegd. Wachtend op herziene versie.

**Comment by niels666** [comment]
HTML en CSS komen er nu aan. Commit in 5 minuten
